import path from 'node:path';
import { fileURLToPath } from 'node:url';
import js from '@eslint/js';
import { FlatCompat } from '@eslint/eslintrc';
import tsPlugin from '@typescript-eslint/eslint-plugin';
import tsParser from '@typescript-eslint/parser';
import reactHooksPlugin from 'eslint-plugin-react-hooks';
import prettierPlugin from 'eslint-plugin-prettier';
import globals from 'globals';

const __dirname = path.dirname(fileURLToPath(import.meta.url));

// eslint-config-airbnb (and plugin:react/recommended, plugin:prettier/recommended)
// don't ship flat-config exports yet - bridge them through FlatCompat rather
// than hand-porting the whole airbnb ruleset. This is the migration path
// ESLint's own docs recommend for exactly this situation.
const compat = new FlatCompat({
  baseDirectory: __dirname,
  recommendedConfig: js.configs.recommended,
});

const legacyConfig = compat.extends(
  'airbnb',
  'plugin:react/recommended',
  'plugin:prettier/recommended',
);

// Rules carried over verbatim from the old .eslintrc.cjs, so this migration
// changes tooling, not behaviour. See todo.md for the follow-up on actually
// fixing the (large, pre-existing) violation count this now surfaces.
const legacyRuleOverrides = {
  'prettier/prettier': 'error',
  'no-console': 'error',
  'react/react-in-jsx-scope': 0,
  'react/jsx-props-no-spreading': 'off',
  'react/forbid-prop-types': 'off',
  'react/prop-types': 'off',
  'no-unsafe-optional-chaining': 'warn',
  'import/no-import-module-exports': 'off',
  'react/function-component-definition': 'off',
  'react/jsx-filename-extension': 'off',
  'import/prefer-default-export': 'warn',
  'react/require-default-props': 'off',
  'object-curly-newline': 'off',
  'no-undef': 0,
  'import/no-unresolved': 0,
  'prefer-template': 1,
  'react/jsx-no-useless-fragment': 0,
  'import/extensions': 0,
  'no-plusplus': 0,
  'no-unused-vars': 'error',
  '@typescript-eslint/no-unused-vars': 'off',
  'class-methods-use-this': 'warn',
  'react/state-in-constructor': 0,
  'react/destructuring-assignment': 0,
  'no-param-reassign': 'warn',
  'jsx-a11y/label-has-associated-control': 'off',
  'jsx-a11y/control-has-associated-label': 'off',
};

export default [
  {
    ignores: [
      'dist/**',
      'src/paraglide/**', // generated by `paraglide-js compile`
      'src/vite-env.d.ts',
      'tailwind.config.js',
      'postcss.config.js',
    ],
  },
  ...legacyConfig,
  {
    files: ['src/**/*.{js,jsx,ts,tsx}'],
    languageOptions: {
      ecmaVersion: 'latest',
      sourceType: 'module',
      globals: { ...globals.browser, ...globals.es2021 },
      parser: tsParser,
      parserOptions: {
        project: ['./tsconfig.json'],
        tsconfigRootDir: __dirname,
        extraFileExtensions: ['.json'],
      },
    },
    plugins: {
      '@typescript-eslint': tsPlugin,
      'react-hooks': reactHooksPlugin,
      prettier: prettierPlugin,
    },
    rules: {
      ...tsPlugin.configs.recommended.rules,
      ...legacyRuleOverrides,
      'react-hooks/rules-of-hooks': 'error',
      'react-hooks/exhaustive-deps': 'warn',
    },
  },
  {
    // Test files import test-only tooling that's correctly a devDependency,
    // not a runtime one - airbnb's import/no-extraneous-dependencies doesn't
    // know that unless told which globs are test files.
    files: ['src/**/*.test.{ts,tsx}', 'src/test/**/*.ts'],
    rules: {
      'import/no-extraneous-dependencies': 'off',
    },
  },
  {
    // Root-level tooling config files: not part of the app's own tsconfig
    // (so no type-aware `project`), and legitimately import devDependencies.
    files: ['*.config.{js,ts,cjs,mjs}'],
    languageOptions: {
      ecmaVersion: 'latest',
      sourceType: 'module',
      globals: { ...globals.node },
      parser: tsParser,
    },
    rules: {
      ...legacyRuleOverrides,
      'import/no-extraneous-dependencies': 'off',
      'import/no-default-export': 'off',
    },
  },
];
