import path from 'node:path';
import { fileURLToPath } from 'node:url';
import js from '@eslint/js';
import { FlatCompat } from '@eslint/eslintrc';
import tsPlugin from '@typescript-eslint/eslint-plugin';
import tsParser from '@typescript-eslint/parser';
import reactHooksPlugin from 'eslint-plugin-react-hooks';
import prettierPlugin from 'eslint-plugin-prettier';
import globals from 'globals';

const __dirname = path.dirname(fileURLToPath(import.meta.url));

// eslint-config-airbnb (and plugin:react/recommended, plugin:prettier/recommended)
// don't ship flat-config exports yet - bridge them through FlatCompat rather
// than hand-porting the whole airbnb ruleset. This is the migration path
// ESLint's own docs recommend for exactly this situation.
const compat = new FlatCompat({
  baseDirectory: __dirname,
  recommendedConfig: js.configs.recommended,
});

const legacyConfig = compat.extends(
  'airbnb',
  'plugin:react/recommended',
  'plugin:prettier/recommended',
);

// Rules carried over verbatim from the old .eslintrc.cjs, so this migration
// changes tooling, not behaviour. See todo.md for the follow-up on actually
// fixing the (large, pre-existing) violation count this now surfaces.
const legacyRuleOverrides = {
  'prettier/prettier': 'error',
  // warn/error are legitimate runtime diagnostics; only bare console.log
  // (debug leftovers) is disallowed.
  'no-console': ['error', { allow: ['warn', 'error'] }],
  'react/react-in-jsx-scope': 0,
  'react/jsx-props-no-spreading': 'off',
  'react/forbid-prop-types': 'off',
  'react/prop-types': 'off',
  'no-unsafe-optional-chaining': 'warn',
  'import/no-import-module-exports': 'off',
  'react/function-component-definition': 'off',
  'react/jsx-filename-extension': 'off',
  'import/prefer-default-export': 'warn',
  'react/require-default-props': 'off',
  'object-curly-newline': 'off',
  'no-undef': 0,
  'import/no-unresolved': 0,
  'prefer-template': 1,
  'react/jsx-no-useless-fragment': 0,
  'import/extensions': 0,
  'no-plusplus': 0,
  // The base rule isn't TypeScript-aware: it flags parameter names in
  // interface/type function signatures (e.g. `onClick: (event: Foo) =>
  // void` inside a props interface) as unused, since it can't tell a
  // type-only signature from a real binding. The typescript-eslint
  // version understands the difference, and also respects the
  // leading-underscore "intentionally unused" convention already used
  // throughout this codebase (e.g. `_properties`, `_imageUrls`).
  'no-unused-vars': 'off',
  '@typescript-eslint/no-unused-vars': [
    'error',
    { argsIgnorePattern: '^_', varsIgnorePattern: '^_' },
  ],
  'class-methods-use-this': 'warn',
  'react/state-in-constructor': 0,
  'react/destructuring-assignment': 0,
  'no-param-reassign': 'warn',
  'jsx-a11y/label-has-associated-control': 'off',
  'jsx-a11y/control-has-associated-label': 'off',
};

export default [
  {
    ignores: [
      'dist/**',
      'src/paraglide/**', // generated by `paraglide-js compile`
      'src/vite-env.d.ts',
      'tailwind.config.js',
      'postcss.config.js',
    ],
  },
  ...legacyConfig,
  {
    files: ['src/**/*.{js,jsx,ts,tsx}'],
    languageOptions: {
      ecmaVersion: 'latest',
      sourceType: 'module',
      globals: { ...globals.browser, ...globals.es2021 },
      parser: tsParser,
      parserOptions: {
        project: ['./tsconfig.json'],
        tsconfigRootDir: __dirname,
        extraFileExtensions: ['.json'],
      },
    },
    plugins: {
      '@typescript-eslint': tsPlugin,
      'react-hooks': reactHooksPlugin,
      prettier: prettierPlugin,
    },
    rules: {
      ...tsPlugin.configs.recommended.rules,
      ...legacyRuleOverrides,
      'react-hooks/rules-of-hooks': 'error',
      'react-hooks/exhaustive-deps': 'warn',
    },
  },
  {
    // Test files import test-only tooling that's correctly a devDependency,
    // not a runtime one - airbnb's import/no-extraneous-dependencies doesn't
    // know that unless told which globs are test files.
    files: ['src/**/*.test.{ts,tsx}', 'src/test/**/*.ts'],
    rules: {
      'import/no-extraneous-dependencies': 'off',
    },
  },
  {
    // Ambient declaration files: `declare namespace JSX { interface
    // IntrinsicElements ... }` is TypeScript declaration merging, not a
    // normal local binding - the base (non-type-aware) no-unused-vars
    // rule can't tell the two apart and flags every merged
    // namespace/interface name as dead code.
    files: ['src/**/*.d.ts'],
    rules: {
      'no-unused-vars': 'off',
    },
  },
  {
    // @ts-nocheck here is a deliberate, documented exception (see the
    // in-file comment): @react-spring/web isn't compatible with React 19's
    // types yet, and the incompatibility cascades across the whole file,
    // not a few isolatable lines. Revisit once that dependency updates -
    // not an eslint-config problem to fix around otherwise.
    files: ['src/views/Tutorial/index.tsx'],
    rules: {
      '@typescript-eslint/ban-ts-comment': 'off',
    },
  },
  {
    // Root-level tooling config files: not part of the app's own tsconfig
    // (so no type-aware `project`), and legitimately import devDependencies.
    files: ['*.config.{js,ts,cjs,mjs}'],
    languageOptions: {
      ecmaVersion: 'latest',
      sourceType: 'module',
      globals: { ...globals.node },
      parser: tsParser,
    },
    plugins: {
      '@typescript-eslint': tsPlugin,
    },
    rules: {
      ...legacyRuleOverrides,
      'import/no-extraneous-dependencies': 'off',
      'import/no-default-export': 'off',
    },
  },
];
